// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY0r4i7KDxX19r3TM-K0ELVC7SVRDowPI',
    appId: '1:239232581730:web:c43a599b5bb9113fadd13b',
    messagingSenderId: '239232581730',
    projectId: 'shopease-c9a3b',
    authDomain: 'shopease-c9a3b.firebaseapp.com',
    storageBucket: 'shopease-c9a3b.firebasestorage.app',
    measurementId: 'G-Z4E1N192D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClr1Snt59-Xm-eIdf-e-QPPXElZzQFGfs',
    appId: '1:239232581730:android:c5e330e897aed119add13b',
    messagingSenderId: '239232581730',
    projectId: 'shopease-c9a3b',
    storageBucket: 'shopease-c9a3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClSOZdHbm6CpoFK9ALKVntJmWSGJIxii8',
    appId: '1:239232581730:ios:9abc54a9efea242cadd13b',
    messagingSenderId: '239232581730',
    projectId: 'shopease-c9a3b',
    storageBucket: 'shopease-c9a3b.firebasestorage.app',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClSOZdHbm6CpoFK9ALKVntJmWSGJIxii8',
    appId: '1:239232581730:ios:9abc54a9efea242cadd13b',
    messagingSenderId: '239232581730',
    projectId: 'shopease-c9a3b',
    storageBucket: 'shopease-c9a3b.firebasestorage.app',
    iosBundleId: 'com.example.shopEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY0r4i7KDxX19r3TM-K0ELVC7SVRDowPI',
    appId: '1:239232581730:web:7faa945ad5f9abc2add13b',
    messagingSenderId: '239232581730',
    projectId: 'shopease-c9a3b',
    authDomain: 'shopease-c9a3b.firebaseapp.com',
    storageBucket: 'shopease-c9a3b.firebasestorage.app',
    measurementId: 'G-NFGJL5NPRJ',
  );
}
